workflow:
    - publish

jobs:
    main:
        image: node:6
        steps:
            - install: cd app && npm install
            - test: cd app && npm test
    publish:
        image: node:6
        steps:
            - build: ./bin/build_package.sh
            - deploy: ./bin/code_deploy.sh
            - test: ./bin/acceptance_test.sh
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
