workflow:
    - publish

jobs:
    main:
        image: node:6
        steps:
            - npm-install: cd app/ && npm install
            - npm-test: npm test
    publish:
        image: node:6
        steps:
            - install-heroku: ./bin/install_heroku.sh
            - heroku-deploy: ./bin/heroku-deploy.sh