jobs:
    main:
        image: node:6
        steps:
            - unittests: cd app/ && npm install && npm test
            - code_deploy: ./bin/code_deploy.sh
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
