workflow:
    - publish

jobs:
    main:
        image: node:6
        steps:
            - npm-install: cd app/ && npm install
            - npm-test: npm test
    publish:
        image: heroku/nodejs:latest
        steps:
            - heroku-deploy: ./bin/heroku_deploy.sh