jobs:
    main:
        image: node:6
        steps:
            - unittests: cd app/ && npm install && npm test
            - ansible_playbook: ./bin/ansible_playbook.sh
        secrets:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
